baseURL = 'https://kalyan.link/'
languageCode = 'en-gb'
title = 'kalyan dutia'
theme = "hugo-bearblog"
[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'blog'
    pageRef = '/blog'
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'
